spring.application.name=notificacion-service
server.port=${SERVER_PORT:8086}

management.server.port=${MANAGEMENT_PORT:8087}
management.endpoints.web.exposure.include=health,info

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:rabbit}
spring.rabbitmq.password=${RABBITMQ_PASS:rabbit123}
